import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AdminSidebar } from "@/components/sidebar";
import { Open_Sans } from "next/font/google";
import StoreProvider from "./Storeprovider";
import { Toaster } from "react-hot-toast";

const opensans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={`${opensans.className} antialiased`}>
          <Toaster position="top-right" reverseOrder={false} />
          <SidebarProvider>
            <AdminSidebar />
            <SidebarInset>
              <header className="sticky top-0 flex h-16 items-center gap-4 border-b bg-background px-4">
                <SidebarTrigger />
                <div className="font-semibold">Admin Dashboard</div>
              </header>
              <main className="flex-1 p-4">{children}</main>
            </SidebarInset>
          </SidebarProvider>
        </body>
      </StoreProvider>
    </html>
  );
}
